apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-exam
  name: golang-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-exam
  template:
    metadata:
      labels:
        app: golang-exam
    spec:
      containers:
      - image: fnabiyev/golang-exam:v1
        name: golang-exam
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64M
        env:
        - name: CPU
          valueFrom:
            resourceFieldRef:
              containerName: golang-exam
              resource: requests.cpu
        - name: MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: golang-exam
              resource: requests.memory
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: info
              key: log_level
        - name: GTPC_PORT
          valueFrom:
            configMapKeyRef:
              name: info
              key: grpc_port
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: info
              key: env
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: database
              key: DB_URI
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        
