apiVersion: v1
items:
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    creationTimestamp: "2024-08-19T12:25:27Z"
    generation: 1
    name: cron-ping
    namespace: exam-1-review
    resourceVersion: "8923473"
    uid: a26c5fd0-526b-4f92-b664-1028e8ce264f
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
        name: cron-ping
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers:
            - command:
              - '''ping'
              - -c
              - "4"
              - 8.8.8.8'
              image: busybox
              imagePullPolicy: Always
              name: cron-ping
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
    schedule: '*/2 * * * *'
    successfulJobsHistoryLimit: 3
    suspend: false
  status:
    active:
    - apiVersion: batch/v1
      kind: Job
      name: cron-ping-28734506
      namespace: exam-1-review
      resourceVersion: "8923468"
      uid: fc48cf46-697d-4411-8531-a7e9285b8dc6
    lastScheduleTime: "2024-08-19T12:26:00Z"
kind: List
metadata:
  resourceVersion: ""
