apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: golang-exam
spec:
  ingressClassName: nginx
  rules:
  - host: nvrbckdown.uz
    http:
      paths:
      - backend:
          service:
            name: golang-exam
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
